# qr_harness.py — shared LEAN-side harness, uploaded unchanged into every QuantConnect project.
#
# Responsibilities (identical for every strategy, so results are comparable):
#   * dates, cash, costs and the holdout lock from qr_params.EXPERIMENT (generated by the runner)
#   * the fixed universe: US common stock, primary share, NYSE/Nasdaq/AMEX, PIT MarketCap >= $2B,
#     plus the tradability filters from the experiment config
#   * execution: orders only from the daily-close hook, always market-on-open for the next session;
#     raw prices for fills, split/dividend-adjusted rolling windows for signals
#   * a self-check of every fill (date strictly after the signal date; price = next open ± slippage)
#   * result export: daily chart "QR" (equity, cash, positions, eligible count) + small QR* log lines
#
# Strategies subclass QRAlgorithm and override the qr_* hooks. They never call market orders directly.
from AlgorithmImports import *
from collections import deque
from datetime import datetime
import json

from qr_params import EXPERIMENT

LAST_UNLOCKED = datetime(2021, 12, 31)
COMMON_STOCK = "ST00000001"
EXCHANGES = ("NYS", "NYSE", "NAS", "ASE", "AMEX")   # old and new Morningstar codes


def slot_weight(n_slots, pv, pf):
    """Weight per position for a strategy with n_slots equal slots: equal weight of the investable
    equity, but never below the minimum position (+1% margin) and never above the weight cap. With
    small equity this raises the weight, and plan_orders' size-aware cap reduces the position count."""
    buffer = float(pf.get("cash_buffer", 0.02))
    max_w = float(pf.get("max_position_weight", 1.0))
    min_pos = float(pf.get("min_position_usd", 0.0))
    w = (1.0 - buffer) / max(int(n_slots), 1)
    if min_pos > 0 and pv > 0:
        w = max(w, 1.01 * min_pos / pv)
    return min(w, max_w)


def plan_orders(items, pv, cash, pf, slip, fee_est, band=0.0, n_open_positions=0):
    """Pure order planning (no LEAN types; unit-tested offline).

    items: [(key, target_weight, last_price, held_qty, pending_qty, delisting_warned)], in priority
           order for new entries. Weight 0 = exit fully.
    pf:    portfolio settings: max_position_weight, cash_buffer, min_position_usd, max_positions.
    Rules: long-only; weights capped at max_position_weight; a NEW position must be worth at least
    min_position_usd (also after any cash scaling); the number of open positions never exceeds
    min(max_positions, floor(pv * (1 - cash_buffer) / min_position_usd)); buys are scaled down so
    that planned cash after sells, fees and slippage stays >= cash_buffer * pv.
    Returns dict(sells=[(key, qty<0)], buys=[(key, qty>0)], skipped_min, skipped_cap, scaled)."""
    max_w = float(pf.get("max_position_weight", 1.0))
    buffer = float(pf.get("cash_buffer", 0.02))
    min_pos = float(pf.get("min_position_usd", 0.0))
    cap = int(pf.get("max_positions", 0)) or None
    if min_pos > 0:
        by_size = int(pv * (1.0 - buffer) // min_pos)
        cap = by_size if cap is None else min(cap, by_size)
    positions = int(n_open_positions)
    sells, buys = [], []
    skipped_min = skipped_cap = 0
    exits_first = [it for it in items if it[1] == 0] + [it for it in items if it[1] != 0]
    for key, w, price, held, pend, warned in exits_first:
        if w < 0:
            raise ValueError("long-only: negative target weight")
        have = held + pend
        if w == 0:
            if have > 0:
                sells.append((key, -int(have), price))
                positions -= 1
            continue
        if price <= 0:
            continue
        w = min(w, max_w)
        target = int(w * pv / price)
        if have > 0:
            delta = target - int(have)
            if band > 0 and abs(delta) * price < band * w * pv:
                continue
            if delta < 0:
                sells.append((key, delta, price))
            elif delta > 0 and not warned:
                buys.append((key, delta, price, False))
            continue
        if warned:
            continue
        if target * price < min_pos:
            skipped_min += 1
            continue
        if cap is not None and positions >= cap:
            skipped_cap += 1
            continue
        buys.append((key, target, price, True))
        positions += 1
    cash_plan = cash + sum(-q * p * (1 - slip) - fee_est(-q) for _, q, p in sells) - buffer * pv
    need = sum(q * p * (1 + slip) + fee_est(q) for _, q, p, _ in buys)
    scale, scaled = 1.0, False
    if need > 0 and cash_plan < need:
        scale, scaled = max(0.0, cash_plan / need), True
    out_buys = []
    for key, q, p, is_new in buys:
        q = int(q * scale)
        if q <= 0:
            continue
        if is_new and q * p < min_pos:
            skipped_min += 1
            continue
        out_buys.append((key, q))
    return dict(sells=[(k, q) for k, q, _ in sells], buys=out_buys, skipped_min=skipped_min,
                skipped_cap=skipped_cap, scaled=scaled)


class FixedPerOrderFeeModel(FeeModel):
    """Owner's actual brokerage cost (D039): a flat fee per EXECUTED order, buy or sell.
    LEAN asks for a fee on every fill event; an order that fills in several pieces is still one
    order, so only its first fill is charged. Orders that never fill are never charged."""

    def __init__(self, per_order):
        super().__init__()
        self.per_order = float(per_order)
        self._charged = set()

    def get_order_fee(self, parameters):
        oid = parameters.order.id
        if oid in self._charged:
            return OrderFee(CashAmount(0.0, "USD"))
        self._charged.add(oid)
        return OrderFee(CashAmount(self.per_order, "USD"))


def is_us_common(f):
    """Common stock, not a depositary receipt, and either Morningstar's primary share or a
    US-domiciled company. The new dataset flags many US companies' only listed share as
    non-primary (GE, BAC, V, DELL, YHOO, … in 2012), so `is_primary_share` alone wrongly drops
    them; foreign companies' secondary US listings (e.g. Canadian banks) stay excluded (D030)."""
    sr = f.security_reference
    if sr.security_type != COMMON_STOCK or sr.is_depositary_receipt:
        return False
    return bool(sr.is_primary_share) or str(f.company_reference.country_id) == "USA"


class QRAlgorithm(QCAlgorithm):
    # ---- strategy-level settings (override in subclasses) ----
    USES_UNIVERSE = False      # subscribe to the >= $2B universe
    WINDOW_BARS = 0            # adjusted close/volume bars kept per subscribed symbol (0 = none)
    FIXED_TICKERS = ()         # extra tickers to subscribe (SPY is always subscribed)

    # ================================================================ setup
    def initialize(self):
        e = EXPERIMENT
        self.qr = e
        start = datetime.strptime(e["start"], "%Y-%m-%d")
        end = datetime.strptime(e["end"], "%Y-%m-%d")
        if end > LAST_UNLOCKED and not e.get("holdout_unlocked", False):
            raise Exception("QR holdout lock: end date after 2021-12-31 without owner unlock")
        self.set_start_date(start.year, start.month, start.day)
        self.set_end_date(end.year, end.month, end.day)
        self.set_cash(float(e["cash"]))
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE, AccountType.MARGIN)
        # base slippage x optional stress multiple (2x/4x/6x robustness runs); commission is separate
        self._qr_slip = float(e["costs"]["slippage_bps"]) * float(e["costs"].get("slippage_stress_multiple", 1)) / 1e4
        # Commission model (D039). Configs without "commission_per_order" are pre-D039 history and
        # keep LEAN's IB per-share model so they remain reproducible.
        per_order = e["costs"].get("commission_per_order")
        if per_order is None:
            self._qr_fee_model = InteractiveBrokersFeeModel()
            self._qr_fee_est = lambda q: max(1.0, 0.005 * q)
        else:
            self._qr_fee_model = FixedPerOrderFeeModel(per_order)
            self._qr_fee_est = lambda q, c=float(per_order): c
        self.set_security_initializer(self._qr_init_security)
        self.universe_settings.resolution = Resolution.DAILY
        self.universe_settings.data_normalization_mode = DataNormalizationMode.RAW
        self.universe_settings.leverage = 1.0

        self.qr_params = e.get("params", {})
        self._qr_u = e.get("universe", {})
        self._qr_pf = e.get("portfolio", {})
        self._qr_in_close = False
        self._qr_last_plot = None
        self._qr_dv = {}                 # symbol -> deque of daily dollar volume (tradability filter)
        self.qr_eligible = []            # eligible symbols as of the previous close
        self.qr_eligible_info = {}       # symbol -> (market_cap, avg dollar volume)
        self.qr_close = {}               # symbol -> deque of adjusted closes (oldest first)
        self.qr_volume = {}              # symbol -> deque of adjusted volumes
        self._qr_last_bar = {}           # symbol -> date of last bar appended
        self._qr_delist_warned = set()
        self._qr_sig = {}                # order id -> signal date string
        self._qr_stats = {
            "days": 0, "orders": 0, "fills": 0, "forced_fills": 0, "invalid": 0,
            "timing_violations": 0, "max_fill_dev": 0.0, "buys_scaled": 0,
            "min_cash_frac": 1.0, "max_gross": 0.0, "elig_min": None, "elig_max": 0,
            "elig_sum": 0, "elig_days": 0, "max_subscribed": 0, "held_splits": 0,
            "held_delistings": 0, "negative_qty": 0,
        }
        self._qr_log_budget = 400        # hard cap on QR* log lines (QC log limit is 100 KB)

        chart = Chart("QR")
        for name in ("equity", "cash", "npos", "nelig"):
            chart.add_series(Series(name, SeriesType.LINE, 0))
        self.add_chart(chart)

        self.spy = self.add_equity("SPY", Resolution.DAILY,
                                   data_normalization_mode=DataNormalizationMode.RAW).symbol
        self.set_benchmark(self.spy)
        self.qr_fixed = {}
        for t in self.FIXED_TICKERS:
            self.qr_fixed[t] = self.add_equity(t, Resolution.DAILY,
                                               data_normalization_mode=DataNormalizationMode.RAW).symbol
        if self.USES_UNIVERSE:
            self.add_universe(self._qr_select)
        self.qr_initialize()

    def _qr_init_security(self, security):
        security.set_fee_model(self._qr_fee_model)
        security.set_slippage_model(ConstantSlippageModel(self._qr_slip))
        # Buying power is not checked by LEAN: MOO sells and buys fill together at the next open,
        # and LEAN would otherwise reject buys funded by same-batch sells. The harness plans cash
        # itself (qr_rebalance), and cash is recorded daily so any borrowing is detected.
        security.set_buying_power_model(BuyingPowerModel.NULL)
        security.set_data_normalization_mode(DataNormalizationMode.RAW)

    # ================================================================ hooks for strategies
    def qr_initialize(self):
        pass

    def qr_select_universe(self, eligible_fundamentals):
        """Return the symbols to subscribe to (default: every eligible symbol)."""
        return [f.symbol for f in eligible_fundamentals]

    def qr_on_close(self, data):
        """Called once per trading day after the close. Place orders only via qr_rebalance."""
        pass

    def qr_on_fill(self, order_event):
        pass

    def qr_on_end(self):
        pass

    # ================================================================ universe
    def _qr_select(self, fundamental):
        u = self._qr_u
        min_cap = float(u.get("min_market_cap", 2e9))
        min_price = float(u.get("min_price", 0.0))
        min_adv = float(u.get("min_avg_dollar_volume", 0.0))
        adv_days = int(u.get("adv_days", 20))
        elig = []
        info = {}
        for f in fundamental:
            if not f.has_fundamental_data:
                continue
            sr = f.security_reference
            if not is_us_common(f):
                continue
            if sr.exchange_id not in EXCHANGES:
                continue
            dq = self._qr_dv.get(f.symbol)
            if dq is None:
                dq = self._qr_dv[f.symbol] = deque(maxlen=adv_days)
            dv = float(f.dollar_volume)
            if dv == dv:                     # skip missing (NaN) volumes; NaN would pass "< min"
                dq.append(dv)
            if f.market_cap < min_cap or f.price < min_price:
                continue
            if len(dq) < adv_days:
                continue
            adv = sum(dq) / len(dq)
            if not adv >= min_adv:
                continue
            elig.append(f)
            info[f.symbol] = (float(f.market_cap), adv)
        self.qr_eligible = [f.symbol for f in elig]
        self.qr_eligible_info = info
        n = len(elig)
        s = self._qr_stats
        s["elig_min"] = n if s["elig_min"] is None else min(s["elig_min"], n)
        s["elig_max"] = max(s["elig_max"], n)
        s["elig_sum"] += n
        s["elig_days"] += 1
        chosen = list(self.qr_select_universe(elig))
        held = [kv.key for kv in self.portfolio if kv.value.invested]
        return list(dict.fromkeys(chosen + held))

    def on_securities_changed(self, changes):
        s = self._qr_stats
        s["max_subscribed"] = max(s["max_subscribed"], len(self.securities))
        if self.WINDOW_BARS <= 0:
            return
        added = [sec.symbol for sec in changes.added_securities if sec.symbol not in self.qr_close]
        if not added:
            return
        # Point-in-time adjusted history (SCALED_RAW adjusts only for actions up to now).
        hist = self.history(added, self.WINDOW_BARS, Resolution.DAILY,
                            data_normalization_mode=DataNormalizationMode.SCALED_RAW)
        for sym in added:
            self.qr_close[sym] = deque(maxlen=self.WINDOW_BARS)
            self.qr_volume[sym] = deque(maxlen=self.WINDOW_BARS)
        if hist is None or hist.empty:
            return
        for (sym, t), row in hist[["close", "volume"]].iterrows():
            if sym in self.qr_close:
                self.qr_close[sym].append(float(row["close"]))
                self.qr_volume[sym].append(float(row["volume"]))
                self._qr_last_bar[sym] = t.date()
        for sec in changes.removed_securities:
            if not self.portfolio[sec.symbol].invested:
                self.qr_close.pop(sec.symbol, None)
                self.qr_volume.pop(sec.symbol, None)
                self._qr_last_bar.pop(sec.symbol, None)

    # ================================================================ data flow
    def on_data(self, data):
        for sym, sp in data.splits.items():
            if sp.type != SplitType.SPLIT_OCCURRED:
                continue
            f = float(sp.split_factor)
            if sym in self.qr_close:
                self.qr_close[sym] = deque((c * f for c in self.qr_close[sym]), maxlen=self.WINDOW_BARS)
                self.qr_volume[sym] = deque((v / f for v in self.qr_volume[sym]), maxlen=self.WINDOW_BARS)
            if self.portfolio[sym].invested:
                self._qr_stats["held_splits"] += 1
                self._qr_log(f"QRSPLIT|{sym.id}|{self.time:%Y-%m-%d}|{f:.10f}")
        for sym, dv in data.dividends.items():
            ref = float(dv.reference_price)
            if sym in self.qr_close and ref > 0:
                k = 1.0 - float(dv.distribution) / ref
                self.qr_close[sym] = deque((c * k for c in self.qr_close[sym]), maxlen=self.WINDOW_BARS)
        for sym, dl in data.delistings.items():
            if dl.type == DelistingType.WARNING:
                self._qr_delist_warned.add(sym)
            elif self.portfolio[sym].invested:
                self._qr_stats["held_delistings"] += 1
                self._qr_log(f"QRDELIST|{sym.id}|{self.time:%Y-%m-%d}|{sym.value}")

        if data.bars.count == 0 or self.time.hour < 9:
            return  # corporate-action-only slice at midnight
        today = self.time.date()
        if self.WINDOW_BARS > 0:
            for sym, bar in data.bars.items():
                dq = self.qr_close.get(sym)
                if dq is None or self._qr_last_bar.get(sym) == today:
                    continue
                dq.append(float(bar.close))
                self.qr_volume[sym].append(float(bar.volume))
                self._qr_last_bar[sym] = today
        if self._qr_last_plot == today:
            return
        self._qr_in_close = True
        try:
            self.qr_on_close(data)
        finally:
            self._qr_in_close = False
        self._qr_record(today)

    def _qr_record(self, today):
        pv = float(self.portfolio.total_portfolio_value)
        cash = float(self.portfolio.cash)
        npos = sum(1 for kv in self.portfolio if kv.value.invested)
        gross = float(self.portfolio.total_holdings_value) / pv if pv > 0 else 0.0
        s = self._qr_stats
        s["days"] += 1
        if pv > 0:
            s["min_cash_frac"] = min(s["min_cash_frac"], cash / pv)
        s["max_gross"] = max(s["max_gross"], gross)
        for kv in self.portfolio:
            if kv.value.quantity < 0:
                s["negative_qty"] += 1
        self.plot("QR", "equity", round(pv, 2))
        self.plot("QR", "cash", round(cash, 2))
        self.plot("QR", "npos", npos)
        self.plot("QR", "nelig", len(self.qr_eligible))
        self._qr_last_plot = today

    # ================================================================ orders
    def qr_rebalance(self, targets, tag="rebal", liquidate_others=False, band=0.0):
        """Queue market-on-open orders so tomorrow's holdings approach `targets` (symbol -> weight
        of current equity; insertion order = priority for new entries). Sizing and all portfolio
        rules live in the pure function plan_orders() below. Returns number of orders placed."""
        if not self._qr_in_close:
            raise Exception("QR timing guard: orders may only be placed from qr_on_close")
        targets = dict(targets)
        if liquidate_others:
            for kv in self.portfolio:
                if kv.value.invested and kv.key not in targets:
                    targets[kv.key] = 0.0
        items = []
        for sym, w in targets.items():
            sec = self.securities[sym] if self.securities.contains_key(sym) else None
            price = float(sec.price) if sec is not None else 0.0
            cur = float(self.portfolio[sym].quantity)
            open_q = sum(float(t.quantity) for t in self.transactions.get_open_order_tickets(sym))
            items.append((sym, float(w), price, cur, open_q, sym in self._qr_delist_warned))
        pending = {}
        for t in self.transactions.get_open_order_tickets():
            pending[t.symbol] = pending.get(t.symbol, 0.0) + float(t.quantity)
        n_open = sum(1 for kv in self.portfolio if kv.value.quantity + pending.get(kv.key, 0.0) > 0)
        n_open += sum(1 for sym, q in pending.items() if q > 0 and not self.portfolio[sym].invested)
        plan = plan_orders(items, float(self.portfolio.total_portfolio_value), float(self.portfolio.cash),
                           self._qr_pf, self._qr_slip, self._qr_fee_est, band, n_open)
        st = self._qr_stats
        st["buys_scaled"] += int(plan["scaled"])
        st["skipped_min_position"] = st.get("skipped_min_position", 0) + plan["skipped_min"]
        st["skipped_max_positions"] = st.get("skipped_max_positions", 0) + plan["skipped_cap"]
        sig = f"{self.time:%Y-%m-%d}"
        n = 0
        for sym, q in plan["sells"] + plan["buys"]:
            n += self._qr_submit(sym, q, f"{tag}|sig={sig}")
        return n

    def qr_slot_weight(self, n_slots):
        return slot_weight(n_slots, float(self.portfolio.total_portfolio_value), self._qr_pf)

    def _qr_submit(self, sym, qty, tag):
        t = self.market_on_open_order(sym, qty, tag=tag)
        self._qr_sig[t.order_id] = tag.rsplit("sig=", 1)[-1]
        self._qr_stats["orders"] += 1
        return 1

    def on_order_event(self, ev):
        s = self._qr_stats
        if ev.status == OrderStatus.INVALID:
            s["invalid"] += 1
            self._qr_log(f"QRINVALID|{ev.symbol.value}|{self.time:%Y-%m-%d}|{ev.message}")
            return
        if ev.status not in (OrderStatus.FILLED, OrderStatus.PARTIALLY_FILLED):
            return
        s["fills"] += 1
        sig = self._qr_sig.get(ev.order_id)
        if sig is None:
            s["forced_fills"] += 1   # e.g. LEAN's delisting liquidation
        else:
            fill_day = self.time.strftime("%Y-%m-%d")
            if fill_day <= sig:
                s["timing_violations"] += 1
                self._qr_log(f"QRTIMING|{ev.symbol.value}|sig={sig}|fill={fill_day}")
            sec = self.securities[ev.symbol]
            expect = float(sec.open) * (1 + self._qr_slip if ev.fill_quantity > 0 else 1 - self._qr_slip)
            if expect > 0:
                dev = abs(float(ev.fill_price) - expect) / expect
                s["max_fill_dev"] = max(s["max_fill_dev"], dev)
                if dev > 1e-6:
                    s["timing_violations"] += 1
                    self._qr_log(f"QRFILLPX|{ev.symbol.value}|{fill_day}|fill={ev.fill_price}|exp={expect:.6f}")
        self.qr_on_fill(ev)

    # ================================================================ end
    def _qr_log(self, line):
        if self._qr_log_budget > 0:
            self._qr_log_budget -= 1
            self.log(line)

    def on_end_of_algorithm(self):
        self.qr_on_end()
        s = dict(self._qr_stats)
        s["elig_mean"] = s["elig_sum"] / s["elig_days"] if s["elig_days"] else 0
        s["open_positions_at_end"] = sum(1 for kv in self.portfolio if kv.value.invested)
        s["log_budget_left"] = self._qr_log_budget
        s["experiment_id"] = self.qr.get("experiment_id")
        self.log("QRSUMMARY|" + json.dumps(s, sort_keys=True))
