# qr_harness.py — shared LEAN-side harness, uploaded unchanged into every QuantConnect project.
#
# Responsibilities (identical for every strategy, so results are comparable):
#   * dates, cash, costs and the holdout lock from qr_params.EXPERIMENT (generated by the runner)
#   * the fixed universe: US common stock, primary share, NYSE/Nasdaq/AMEX, PIT MarketCap >= $2B,
#     plus the tradability filters from the experiment config
#   * execution: orders only from the daily-close hook, always market-on-open for the next session;
#     raw prices for fills, split/dividend-adjusted rolling windows for signals
#   * a self-check of every fill (date strictly after the signal date; price = next open ± slippage)
#   * result export: daily chart "QR" (equity, cash, positions, eligible count) + small QR* log lines
#
# Strategies subclass QRAlgorithm and override the qr_* hooks. They never call market orders directly.
from AlgorithmImports import *
from collections import deque
from datetime import datetime
import json
import re

from qr_params import EXPERIMENT

LAST_UNLOCKED = datetime(2021, 12, 31)
COMMON_STOCK = "ST00000001"
EXCHANGES = ("NYS", "NYSE", "NAS", "ASE", "AMEX")   # old and new Morningstar codes
STALE_SESSIONS = 10      # D059: a holding with no real price bar for this many sessions is terminated
STALE_ORDER_SESSIONS = 5  # D059: a harness order still open after this many sessions fails the run


def slot_weight(n_slots, pv, pf):
    """Weight per position for a strategy with n_slots equal slots: equal weight of the investable
    equity, but never below the minimum position (+1% margin) and never above the weight cap. With
    small equity this raises the weight, and plan_orders' size-aware cap reduces the position count."""
    buffer = float(pf.get("cash_buffer", 0.02))
    max_w = float(pf.get("max_position_weight", 1.0))
    min_pos = float(pf.get("min_position_usd", 0.0))
    w = (1.0 - buffer) / max(int(n_slots), 1)
    if min_pos > 0 and pv > 0:
        w = max(w, 1.01 * min_pos / pv)
    return min(w, max_w)


def plan_orders(items, pv, cash, pf, slip, fee_est, band=0.0, n_open_positions=0):
    """Pure order planning (no LEAN types; unit-tested offline).

    items: [(key, target_weight, last_price, held_qty, pending_qty, delisting_warned)], in priority
           order for new entries. Weight 0 = exit fully.
    pf:    portfolio settings: max_position_weight, cash_buffer, min_position_usd, max_positions.
    Rules: long-only; weights capped at max_position_weight; a NEW position must be worth at least
    min_position_usd (also after any cash scaling); the number of open positions never exceeds
    min(max_positions, floor(pv * (1 - cash_buffer) / min_position_usd)); buys are scaled down so
    that planned cash after sells, fees and slippage stays >= cash_buffer * pv.
    Returns dict(sells=[(key, qty<0)], buys=[(key, qty>0)], skipped_min, skipped_cap, scaled)."""
    max_w = float(pf.get("max_position_weight", 1.0))
    buffer = float(pf.get("cash_buffer", 0.02))
    min_pos = float(pf.get("min_position_usd", 0.0))
    cap = int(pf.get("max_positions", 0)) or None
    # D051: "settled_cash_only" = buys are funded only by cash already held; proceeds of sells in the
    # same batch (and the slots they free) become usable only after those sells have executed.
    settled_only = pf.get("buy_funding") == "settled_cash_only"
    gap = float(pf.get("gap_reserve", 0.0))
    if min_pos > 0:
        by_size = int(pv * (1.0 - buffer) // min_pos)
        cap = by_size if cap is None else min(cap, by_size)
    positions = int(n_open_positions)
    sells, buys = [], []
    skipped_min = skipped_cap = 0
    exits_first = [it for it in items if it[1] == 0] + [it for it in items if it[1] != 0]
    for key, w, price, held, pend, warned in exits_first:
        if w < 0:
            raise ValueError("long-only: negative target weight")
        have = held + pend
        if w == 0:
            if have > 0:
                sells.append((key, -int(have), price))
                if not settled_only:
                    positions -= 1
            continue
        if price <= 0:
            continue
        w = min(w, max_w)
        target = int(w * pv / price)
        if have > 0:
            delta = target - int(have)
            if band > 0 and abs(delta) * price < band * w * pv:
                continue
            if delta < 0:
                sells.append((key, delta, price))
            elif delta > 0 and not warned:
                buys.append((key, delta, price, False))
            continue
        if warned:
            continue
        if target * price < min_pos:
            skipped_min += 1
            continue
        if cap is not None and positions >= cap:
            skipped_cap += 1
            continue
        buys.append((key, target, price, True))
        positions += 1
    if settled_only:
        # sells still pay their own fees out of cash; their proceeds are not counted
        cash_plan = cash - sum(fee_est(-q) for _, q, _ in sells) - buffer * pv
    else:
        cash_plan = cash + sum(-q * p * (1 - slip) - fee_est(-q) for _, q, p in sells) - buffer * pv
    need = sum(q * p * (1 + slip) * (1 + gap) + fee_est(q) for _, q, p, _ in buys)
    scale, scaled = 1.0, False
    if need > 0 and cash_plan < need:
        scale, scaled = max(0.0, cash_plan / need), True
    out_buys = []
    for key, q, p, is_new in buys:
        q = int(q * scale)
        if q <= 0:
            continue
        if is_new and q * p < min_pos:
            skipped_min += 1
            continue
        out_buys.append((key, q))
    return dict(sells=[(k, q) for k, q, _ in sells], buys=out_buys, skipped_min=skipped_min,
                skipped_cap=skipped_cap, scaled=scaled)


class FixedPerOrderFeeModel(FeeModel):
    """Owner's actual brokerage cost (D039): a flat fee per EXECUTED order, buy or sell.
    LEAN asks for a fee on every fill event; an order that fills in several pieces is still one
    order, so only its first fill is charged. Orders that never fill are never charged."""

    def __init__(self, per_order):
        super().__init__()
        self.per_order = float(per_order)
        self._charged = set()

    def get_order_fee(self, parameters):
        oid = parameters.order.id
        if oid in self._charged:
            return OrderFee(CashAmount(0.0, "USD"))
        self._charged.add(oid)
        return OrderFee(CashAmount(self.per_order, "USD"))


# D057: instruments Morningstar labels "common stock" that are not operating-company common stock.
# Morningstar's company flags describe a company's CURRENT status (an acquired corporation that is
# now an LLC subsidiary is flagged LLC), so the LLC flag only counts when the share class itself
# is described as LLC units; the partnership flag has no such false positives (E956-01 audit).
NON_COMMON_SIC = {6726: "closed-end fund / unit investment trust", 6770: "blank-check company",
                  6792: "oil royalty trust"}
_LLC_TEXT = re.compile(r"\bL\.?L\.?C\b", re.I)
_LLC_CLASS = re.compile(r"\bL\.?L\.?C\b.*\b(Class|Units?|Shs|Shares|Interests?)\b", re.I)
_LP_CLASS = re.compile(r"\bL\.P\.|\bLimited Partnership\b|\bPartnership Units?\b|\bCommon Units?\b|\bLP Units?\b", re.I)
# Dated corrections where the current-status fields are wrong for part of history (public facts).
# sid -> ((from, to_inclusive, verdict), ...): verdict None = ordinary common stock, str = excluded.
UNIVERSE_OVERRIDES = {
    "YHOO R735QTJ8XC9X": (("1900-01-01", "2017-06-16", None),),   # Yahoo until it became the fund Altaba
    "BX TTO1M4GXI99H": (("2019-07-01", "2999-12-31", None),),     # Blackstone: LP units until 2019-07-01
    "CG V69R09HVGXGL": (("2020-01-01", "2999-12-31", None),),     # Carlyle: LP units until 2020-01-01
    "BUR XIT9T96LYYJP": (("1900-01-01", "2999-12-31", None),),    # Burford Capital: operating company
    "ACAS R735QTJ8XC9X": (("1900-01-01", "2999-12-31", "business development company (fund)"),),
}


def _attr(obj, name, default=None):
    try:
        v = getattr(obj, name)
    except Exception:
        return default
    return default if v is None else v


def non_common_reason(f, day=None):
    """Why a security that Morningstar calls common stock is not an eligible US common stock
    (D057), or None if it is eligible. `day` (YYYY-MM-DD) applies the dated overrides."""
    sid = str(f.symbol.id)
    if day is not None:
        for a, b, verdict in UNIVERSE_OVERRIDES.get(sid, ()):
            if a <= day <= b:
                return verdict
    cr, sr, ac = f.company_reference, f.security_reference, f.asset_classification
    sc = str(_attr(sr, "share_class_description", "") or "")
    if bool(_attr(cr, "is_limited_partnership", False)):
        return "limited partnership units"
    if bool(_attr(cr, "is_limited_liability_company", False)) and _LLC_TEXT.search(sc):
        return "LLC units"
    if _LLC_CLASS.search(sc):
        return "LLC units (share class)"
    if _LP_CLASS.search(sc):
        return "partnership units (share class)"
    if str(_attr(cr, "industry_template_code", "")) == "V":
        return "investment vehicle (closed-end fund / BDC)"
    try:
        sic = int(_attr(ac, "sic", 0) or 0)
    except (TypeError, ValueError):
        sic = 0
    return NON_COMMON_SIC.get(sic)


def is_us_common(f, day=None):
    """Common stock, not a depositary receipt, and either Morningstar's primary share or a
    US-domiciled company. The new dataset flags many US companies' only listed share as
    non-primary (GE, BAC, V, DELL, YHOO, … in 2012), so `is_primary_share` alone wrongly drops
    them; foreign companies' secondary US listings (e.g. Canadian banks) stay excluded (D030).
    Funds, BDCs, partnership and LLC units, royalty trusts and blank-check companies that
    Morningstar also labels common stock are excluded (D057, `non_common_reason`)."""
    sr = f.security_reference
    if sr.security_type != COMMON_STOCK or sr.is_depositary_receipt:
        return False
    if not (bool(sr.is_primary_share) or str(f.company_reference.country_id) == "USA"):
        return False
    return non_common_reason(f, day) is None


class QRAlgorithm(QCAlgorithm):
    # ---- strategy-level settings (override in subclasses) ----
    USES_UNIVERSE = False      # subscribe to the >= $2B universe
    WINDOW_BARS = 0            # adjusted close/volume bars kept per subscribed symbol (0 = none)
    FIXED_TICKERS = ()         # extra tickers to subscribe (SPY is always subscribed)

    # ================================================================ setup
    def initialize(self):
        e = EXPERIMENT
        self.qr = e
        start = datetime.strptime(e["start"], "%Y-%m-%d")
        end = datetime.strptime(e["end"], "%Y-%m-%d")
        if end > LAST_UNLOCKED and not e.get("holdout_unlocked", False):
            raise Exception("QR holdout lock: end date after 2021-12-31 without owner unlock")
        self.set_start_date(start.year, start.month, start.day)
        self.set_end_date(end.year, end.month, end.day)
        self.set_cash(float(e["cash"]))
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE, AccountType.MARGIN)
        # base slippage x optional stress multiple (2x/4x/6x robustness runs); commission is separate
        self._qr_slip = float(e["costs"]["slippage_bps"]) * float(e["costs"].get("slippage_stress_multiple", 1)) / 1e4
        # Commission model (D039). Configs without "commission_per_order" are pre-D039 history and
        # keep LEAN's IB per-share model so they remain reproducible.
        per_order = e["costs"].get("commission_per_order")
        if per_order is None:
            self._qr_fee_model = InteractiveBrokersFeeModel()
            self._qr_fee_est = lambda q: max(1.0, 0.005 * q)
            self._qr_forced_fee = 0.0          # legacy configs: behaviour unchanged
        else:
            self._qr_fee_model = FixedPerOrderFeeModel(per_order)
            self._qr_fee_est = lambda q, c=float(per_order): c
            self._qr_forced_fee = float(per_order)
        self._qr_forced_debited = set()
        self._qr_resubmit = {}             # symbol -> quantity of a harness sell cancelled on a ticker change
        self.set_security_initializer(self._qr_init_security)
        self.universe_settings.resolution = Resolution.DAILY
        self.universe_settings.data_normalization_mode = DataNormalizationMode.RAW
        self.universe_settings.leverage = 1.0

        self.qr_params = e.get("params", {})
        self._qr_u = e.get("universe", {})
        self._qr_pf = e.get("portfolio", {})
        self._qr_in_close = False
        self._qr_last_plot = None
        self._qr_dv = {}                 # symbol -> deque of daily dollar volume (tradability filter)
        self.qr_eligible = []            # eligible symbols as of the previous close
        self.qr_eligible_info = {}       # symbol -> (market_cap, avg dollar volume)
        self.qr_close = {}               # symbol -> deque of adjusted closes (oldest first)
        self.qr_volume = {}              # symbol -> deque of adjusted volumes
        self._qr_last_bar = {}           # symbol -> date of last bar appended
        self._qr_delist_warned = set()
        # D059: last real (not filled-forward) bar per symbol, counted in trading sessions (SPY bars)
        self._qr_session = 0
        self._qr_session_day = None
        self._qr_real_session = {}
        self._qr_real_close = {}
        self._qr_real_date = {}
        self._qr_terminated = set()
        self._qr_order_session = {}
        self._qr_sig = {}                # order id -> signal date string
        self._qr_stats = {
            "days": 0, "orders": 0, "fills": 0, "forced_fills": 0, "invalid": 0,
            "timing_violations": 0, "max_fill_dev": 0.0, "buys_scaled": 0,
            "min_cash_frac": 1.0, "max_gross": 0.0, "elig_min": None, "elig_max": 0,
            "elig_sum": 0, "elig_days": 0, "max_subscribed": 0, "held_splits": 0,
            "held_delistings": 0, "negative_qty": 0, "forced_fee_debits": 0,
            "cancelled_harness_sells": 0, "cancelled_harness_buys": 0, "cancelled_on_symbol_change": 0,
            "cancelled_sells_delisting": 0, "resubmitted_sells": 0,
            "stale_exits": 0, "stale_unresolved": 0, "stale_open_orders": 0, "cancelled_stale": 0,
        }
        # QR* result lines are NOT written to QuantConnect logs (daily quota). They are collected here
        # and published at the end as summary statistics, read back via the backtests/read API (D046).
        self._qr_msgs = []
        self._qr_log_budget = 20000      # hard cap on result lines kept

        chart = Chart("QR")
        for name in ("equity", "cash", "npos", "nelig"):
            chart.add_series(Series(name, SeriesType.LINE, 0))
        self.add_chart(chart)

        self.spy = self.add_equity("SPY", Resolution.DAILY,
                                   data_normalization_mode=DataNormalizationMode.RAW).symbol
        self.set_benchmark(self.spy)
        self.qr_fixed = {}
        for t in self.FIXED_TICKERS:
            self.qr_fixed[t] = self.add_equity(t, Resolution.DAILY,
                                               data_normalization_mode=DataNormalizationMode.RAW).symbol
        if self.USES_UNIVERSE:
            self.add_universe(self._qr_select)
        self.qr_initialize()

    def _qr_init_security(self, security):
        security.set_fee_model(self._qr_fee_model)
        security.set_slippage_model(ConstantSlippageModel(self._qr_slip))
        # Buying power is not checked by LEAN: MOO sells and buys fill together at the next open,
        # and LEAN would otherwise reject buys funded by same-batch sells. The harness plans cash
        # itself (qr_rebalance), and cash is recorded daily so any borrowing is detected.
        security.set_buying_power_model(BuyingPowerModel.NULL)
        security.set_data_normalization_mode(DataNormalizationMode.RAW)

    # ================================================================ hooks for strategies
    def qr_initialize(self):
        pass

    def qr_select_universe(self, eligible_fundamentals):
        """Return the symbols to subscribe to (default: every eligible symbol)."""
        return [f.symbol for f in eligible_fundamentals]

    def qr_on_close(self, data):
        """Called once per trading day after the close. Place orders only via qr_rebalance."""
        pass

    def qr_on_fill(self, order_event):
        pass

    def qr_on_end(self):
        pass

    # ================================================================ universe
    def _qr_select(self, fundamental):
        u = self._qr_u
        min_cap = float(u.get("min_market_cap", 2e9))
        min_price = float(u.get("min_price", 0.0))
        min_adv = float(u.get("min_avg_dollar_volume", 0.0))
        adv_days = int(u.get("adv_days", 20))
        elig = []
        info = {}
        day = self.time.strftime("%Y-%m-%d")
        for f in fundamental:
            if not f.has_fundamental_data:
                continue
            sr = f.security_reference
            if not is_us_common(f, day):
                continue
            if sr.exchange_id not in EXCHANGES:
                continue
            dq = self._qr_dv.get(f.symbol)
            if dq is None:
                dq = self._qr_dv[f.symbol] = deque(maxlen=adv_days)
            dv = float(f.dollar_volume)
            if dv == dv:                     # skip missing (NaN) volumes; NaN would pass "< min"
                dq.append(dv)
            if f.market_cap < min_cap or f.price < min_price:
                continue
            if len(dq) < adv_days:
                continue
            adv = sum(dq) / len(dq)
            if not adv >= min_adv:
                continue
            elig.append(f)
            info[f.symbol] = (float(f.market_cap), adv)
        self.qr_eligible = [f.symbol for f in elig]
        self.qr_eligible_info = info
        n = len(elig)
        s = self._qr_stats
        s["elig_min"] = n if s["elig_min"] is None else min(s["elig_min"], n)
        s["elig_max"] = max(s["elig_max"], n)
        s["elig_sum"] += n
        s["elig_days"] += 1
        chosen = list(self.qr_select_universe(elig))
        held = [kv.key for kv in self.portfolio if kv.value.invested]
        return list(dict.fromkeys(chosen + held))

    def on_securities_changed(self, changes):
        s = self._qr_stats
        s["max_subscribed"] = max(s["max_subscribed"], len(self.securities))
        if self.WINDOW_BARS <= 0:
            return
        added = [sec.symbol for sec in changes.added_securities if sec.symbol not in self.qr_close]
        if not added:
            return
        # Point-in-time adjusted history (SCALED_RAW adjusts only for actions up to now).
        hist = self.history(added, self.WINDOW_BARS, Resolution.DAILY,
                            data_normalization_mode=DataNormalizationMode.SCALED_RAW)
        for sym in added:
            self.qr_close[sym] = deque(maxlen=self.WINDOW_BARS)
            self.qr_volume[sym] = deque(maxlen=self.WINDOW_BARS)
        if hist is None or hist.empty:
            return
        for (sym, t), row in hist[["close", "volume"]].iterrows():
            if sym in self.qr_close:
                self.qr_close[sym].append(float(row["close"]))
                self.qr_volume[sym].append(float(row["volume"]))
                self._qr_last_bar[sym] = t.date()
        for sec in changes.removed_securities:
            if not self.portfolio[sec.symbol].invested:
                self.qr_close.pop(sec.symbol, None)
                self.qr_volume.pop(sec.symbol, None)
                self._qr_last_bar.pop(sec.symbol, None)

    # ================================================================ data flow
    def on_data(self, data):
        for sym, sp in data.splits.items():
            if sp.type != SplitType.SPLIT_OCCURRED:
                continue
            f = float(sp.split_factor)
            if sym in self.qr_close:
                self.qr_close[sym] = deque((c * f for c in self.qr_close[sym]), maxlen=self.WINDOW_BARS)
                self.qr_volume[sym] = deque((v / f for v in self.qr_volume[sym]), maxlen=self.WINDOW_BARS)
            if self.portfolio[sym].invested:
                self._qr_stats["held_splits"] += 1
                self._qr_log(f"QRSPLIT|{sym.id}|{self.time:%Y-%m-%d}|{f:.10f}")
        for sym, dv in data.dividends.items():
            ref = float(dv.reference_price)
            if sym in self.qr_close and ref > 0:
                k = 1.0 - float(dv.distribution) / ref
                self.qr_close[sym] = deque((c * k for c in self.qr_close[sym]), maxlen=self.WINDOW_BARS)
        for sym, dl in data.delistings.items():
            if dl.type == DelistingType.WARNING:
                self._qr_delist_warned.add(sym)
            elif self.portfolio[sym].invested:
                self._qr_stats["held_delistings"] += 1
                self._qr_log(f"QRDELIST|{sym.id}|{self.time:%Y-%m-%d}|{sym.value}")

        if data.bars.count == 0 or self.time.hour < 9:
            return  # corporate-action-only slice at midnight
        today = self.time.date()
        self._qr_track_real_bars(data, today)
        if self.WINDOW_BARS > 0:
            for sym, bar in data.bars.items():
                dq = self.qr_close.get(sym)
                if dq is None or self._qr_last_bar.get(sym) == today:
                    continue
                dq.append(float(bar.close))
                self.qr_volume[sym].append(float(bar.volume))
                self._qr_last_bar[sym] = today
        if self._qr_last_plot == today:
            return
        self._qr_in_close = True
        try:
            self._qr_check_stale(today)
            self._qr_resubmit_cancelled()
            self.qr_on_close(data)
        finally:
            self._qr_in_close = False
        self._qr_record(today)

    # ================================================================ D059 stale holdings
    def _qr_track_real_bars(self, data, today):
        """Count trading sessions (real SPY bars) and remember each symbol's last real bar."""
        if self._qr_session_day != today and data.bars.contains_key(self.spy) \
                and not data.bars[self.spy].is_fill_forward:
            self._qr_session += 1
            self._qr_session_day = today
        for sym, bar in data.bars.items():
            if not bar.is_fill_forward:
                self._qr_real_session[sym] = self._qr_session
                self._qr_real_close[sym] = float(bar.close)
                self._qr_real_date[sym] = today

    def _qr_check_stale(self, today):
        """A held security with no real price bar for more than STALE_SESSIONS trading sessions has
        become untradeable (e.g. acquired without a delisting event in the data). It is taken out of
        the portfolio at its LAST REAL CLOSE from the data stream, as LEAN does for a delisting, with
        the fixed commission; open orders for it are cancelled and the event is logged (QRSTALE)."""
        for kv in list(self.portfolio):
            sym, h = kv.key, kv.value
            if not h.invested or sym in self._qr_terminated:
                continue
            last = self._qr_real_session.get(sym)
            if last is None:
                self._qr_real_session[sym] = self._qr_session   # first sight: start counting now
                continue
            if self._qr_session - last > STALE_SESSIONS:
                self._qr_terminate(sym, today)

    def _qr_terminate(self, sym, today):
        qty = float(self.portfolio[sym].quantity)
        price = self._qr_real_close.get(sym)
        if price is None or qty <= 0:
            self._qr_stats["stale_unresolved"] += 1
            self._qr_log(f"QRSTALE_UNRESOLVED|{sym.id}|{sym.value}|{today:%Y-%m-%d}|{qty}")
            return
        self._qr_terminated.add(sym)
        self._qr_resubmit.pop(sym, None)
        self.transactions.cancel_open_orders(sym)
        fee = float(self._qr_forced_fee or 0.0)
        self.portfolio[sym].set_holdings(price, 0)
        self.portfolio.cash_book["USD"].add_amount(qty * price - fee)
        self._qr_stats["stale_exits"] += 1
        self._qr_log(f"QRSTALE|{sym.id}|{sym.value}|{self._qr_real_date[sym]:%Y-%m-%d}|{today:%Y-%m-%d}"
                     f"|{qty}|{price:.6f}|{fee:.2f}")

    def _qr_record(self, today):
        pv = float(self.portfolio.total_portfolio_value)
        cash = float(self.portfolio.cash)
        npos = sum(1 for kv in self.portfolio if kv.value.invested)
        gross = float(self.portfolio.total_holdings_value) / pv if pv > 0 else 0.0
        s = self._qr_stats
        s["days"] += 1
        if pv > 0:
            s["min_cash_frac"] = min(s["min_cash_frac"], cash / pv)
        s["max_gross"] = max(s["max_gross"], gross)
        for kv in self.portfolio:
            if kv.value.quantity < 0:
                s["negative_qty"] += 1
        self.plot("QR", "equity", round(pv, 2))
        self.plot("QR", "cash", round(cash, 2))
        self.plot("QR", "npos", npos)
        self.plot("QR", "nelig", len(self.qr_eligible))
        self._qr_last_plot = today

    # ================================================================ orders
    def qr_rebalance(self, targets, tag="rebal", liquidate_others=False, band=0.0):
        """Queue market-on-open orders so tomorrow's holdings approach `targets` (symbol -> weight
        of current equity; insertion order = priority for new entries). Sizing and all portfolio
        rules live in the pure function plan_orders() below. Returns number of orders placed."""
        if not self._qr_in_close:
            raise Exception("QR timing guard: orders may only be placed from qr_on_close")
        targets = dict(targets)
        if liquidate_others:
            for kv in self.portfolio:
                if kv.value.invested and kv.key not in targets:
                    targets[kv.key] = 0.0
        items = []
        for sym, w in targets.items():
            sec = self.securities[sym] if self.securities.contains_key(sym) else None
            price = float(sec.price) if sec is not None else 0.0
            cur = float(self.portfolio[sym].quantity)
            open_q = sum(float(t.quantity) for t in self.transactions.get_open_order_tickets(sym))
            items.append((sym, float(w), price, cur, open_q, sym in self._qr_delist_warned))
        pending = {}
        for t in self.transactions.get_open_order_tickets():
            pending[t.symbol] = pending.get(t.symbol, 0.0) + float(t.quantity)
        n_open = sum(1 for kv in self.portfolio if kv.value.quantity + pending.get(kv.key, 0.0) > 0)
        n_open += sum(1 for sym, q in pending.items() if q > 0 and not self.portfolio[sym].invested)
        plan = plan_orders(items, float(self.portfolio.total_portfolio_value), float(self.portfolio.cash),
                           self._qr_pf, self._qr_slip, self._qr_fee_est, band, n_open)
        st = self._qr_stats
        st["buys_scaled"] += int(plan["scaled"])
        st["skipped_min_position"] = st.get("skipped_min_position", 0) + plan["skipped_min"]
        st["skipped_max_positions"] = st.get("skipped_max_positions", 0) + plan["skipped_cap"]
        sig = f"{self.time:%Y-%m-%d}"
        n = 0
        for sym, q in plan["sells"] + plan["buys"]:
            n += self._qr_submit(sym, q, f"{tag}|sig={sig}")
        return n

    def _qr_resubmit_cancelled(self):
        """Re-issue harness sells that LEAN cancelled on a ticker change (D051), capped at the held
        quantity, as market-on-open orders from this close."""
        sig = f"{self.time:%Y-%m-%d}"
        for sym, q in list(self._qr_resubmit.items()):
            del self._qr_resubmit[sym]
            held = float(self.portfolio[sym].quantity)
            pending = sum(float(t.quantity) for t in self.transactions.get_open_order_tickets(sym))
            qty = -int(min(held + min(pending, 0.0), -q))
            if qty < 0:
                self._qr_submit(sym, qty, f"resub|sig={sig}")
                self._qr_stats["resubmitted_sells"] += 1

    def qr_slot_weight(self, n_slots):
        return slot_weight(n_slots, float(self.portfolio.total_portfolio_value), self._qr_pf)

    def _qr_submit(self, sym, qty, tag):
        t = self.market_on_open_order(sym, qty, tag=tag)
        self._qr_sig[t.order_id] = tag.rsplit("sig=", 1)[-1]
        self._qr_order_session[t.order_id] = self._qr_session
        self._qr_stats["orders"] += 1
        return 1

    def on_order_event(self, ev):
        s = self._qr_stats
        if ev.status == OrderStatus.CANCELED and ev.symbol in self._qr_terminated:
            s["cancelled_stale"] += 1              # cancelled by the D059 fallback itself: never re-issued
            return
        if ev.status == OrderStatus.CANCELED and self._qr_sig.get(ev.order_id) is not None:
            # The harness never cancels its own orders, so every cancellation here is LEAN's: a ticker
            # change (LEAN rewrites the order tag; the event message is empty, D054) or a delisting.
            order = self.transactions.get_order_by_id(ev.order_id)
            reason = str(getattr(order, "tag", "") or "") + " " + str(ev.message or "")
            if "symbol changed" in reason.lower():
                s["cancelled_on_symbol_change"] += 1
            if float(ev.quantity) >= 0:
                s["cancelled_harness_buys"] += 1      # not re-issued: the strategy re-selects on later days
                return
            s["cancelled_harness_sells"] += 1
            if ev.symbol in self._qr_delist_warned:
                s["cancelled_sells_delisting"] += 1   # LEAN liquidates delisted holdings itself
                return
            # D051/D054: the exit must still happen; re-issue it at the next close
            self._qr_resubmit[ev.symbol] = float(ev.quantity)
            self._qr_log(f"QRRESUB|{ev.symbol.value}|{self.time:%Y-%m-%d}|{ev.quantity}")
            return
        if ev.status == OrderStatus.INVALID:
            s["invalid"] += 1
            self._qr_log(f"QRINVALID|{ev.symbol.value}|{self.time:%Y-%m-%d}|{ev.message}")
            return
        if ev.status not in (OrderStatus.FILLED, OrderStatus.PARTIALLY_FILLED):
            return
        s["fills"] += 1
        sig = self._qr_sig.get(ev.order_id)
        if sig is None:
            s["forced_fills"] += 1   # e.g. LEAN's delisting liquidation
            # LEAN executes delisting liquidations with a zero fee, bypassing the fee model. Under the
            # fixed per-order model every executed order costs the commission (D039/D049), so debit it
            # here, once per order, and record it so the local accounting can mirror the debit.
            if self._qr_forced_fee and float(ev.order_fee.value.amount) == 0 \
                    and ev.order_id not in self._qr_forced_debited:
                self._qr_forced_debited.add(ev.order_id)
                self.portfolio.cash_book["USD"].add_amount(-self._qr_forced_fee)
                s["forced_fee_debits"] = s.get("forced_fee_debits", 0) + 1
                self._qr_log(f"QRFORCEDFEE|{ev.order_id}|{self._qr_forced_fee:.2f}")
        else:
            fill_day = self.time.strftime("%Y-%m-%d")
            if fill_day <= sig:
                s["timing_violations"] += 1
                self._qr_log(f"QRTIMING|{ev.symbol.value}|sig={sig}|fill={fill_day}")
            sec = self.securities[ev.symbol]
            expect = float(sec.open) * (1 + self._qr_slip if ev.fill_quantity > 0 else 1 - self._qr_slip)
            if expect > 0:
                dev = abs(float(ev.fill_price) - expect) / expect
                s["max_fill_dev"] = max(s["max_fill_dev"], dev)
                if dev > 1e-6:
                    s["timing_violations"] += 1
                    self._qr_log(f"QRFILLPX|{ev.symbol.value}|{fill_day}|fill={ev.fill_price}|exp={expect:.6f}")
        self.qr_on_fill(ev)

    # ================================================================ end
    def _qr_log(self, line):
        if self._qr_log_budget > 0:
            self._qr_log_budget -= 1
            self._qr_msgs.append(str(line))

    def on_end_of_algorithm(self):
        self.qr_on_end()
        for t in self.transactions.get_open_order_tickets():
            if self._qr_session - self._qr_order_session.get(t.order_id, self._qr_session) > STALE_ORDER_SESSIONS:
                self._qr_stats["stale_open_orders"] += 1
                self._qr_log(f"QRSTALEORDER|{t.order_id}|{t.symbol.value}|{t.quantity}")
        for kv in self.portfolio:
            last = self._qr_real_session.get(kv.key)
            if kv.value.invested and last is not None and self._qr_session - last > STALE_SESSIONS:
                self._qr_stats["stale_unresolved"] += 1
        s = dict(self._qr_stats)
        s["elig_mean"] = s["elig_sum"] / s["elig_days"] if s["elig_days"] else 0
        s["open_positions_at_end"] = sum(1 for kv in self.portfolio if kv.value.invested)
        s["log_budget_left"] = self._qr_log_budget
        s["experiment_id"] = self.qr.get("experiment_id")
        self._qr_publish(json.dumps(s, sort_keys=True))

    def _qr_publish(self, summary_json):
        """Publish results as summary statistics (keys qr_summary, qr_msgs_n, qr_msgs_00...), each value
        at most 150,000 characters (QC returns 200,000-character values intact)."""
        self.set_summary_statistic("qr_summary", summary_json)
        text = "\n".join(self._qr_msgs)
        chunks = [text[i:i + 150000] for i in range(0, len(text), 150000)] if text else []
        self.set_summary_statistic("qr_msgs_n", str(len(chunks)))
        for i, c in enumerate(chunks):
            self.set_summary_statistic(f"qr_msgs_{i:02d}", c)
