"""Render the data-audit experiment (X951) into docs/data/data_audit.md and audit_monthly.csv.

    python -m qresearch.audit E951-01
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

from . import config, results


def parse_messages(lines: list[str]) -> dict:
    monthly, snaps, examples, track = [], [], [], {}
    for ln in lines:
        if ln.startswith("QRAUDIT_M|"):
            _, day, js = ln.split("|", 2)
            monthly.append(dict(date=day, **json.loads(js)))
        elif ln.startswith("QRAUDIT_SNAP|"):
            parts = ln.split("|")
            d = dict(target=parts[1], date=parts[2], ticker=parts[3])
            for kv in parts[4:]:
                k, _, v = kv.partition("=")
                d[k] = v
            snaps.append(d)
        elif ln.startswith("QRAUDIT_EX|"):
            _, day, z, nf = ln.split("|", 3)
            examples.append(dict(date=day, zero_cap_common=z.split("=", 1)[1], no_fundamentals=nf.split("=", 1)[1]))
        elif ln.startswith("QRAUDIT_TRACK|"):
            track = json.loads(ln.split("|", 1)[1])
    return dict(monthly=pd.DataFrame(monthly), snaps=snaps, examples=examples, track=track)


def yearly_table(monthly: pd.DataFrame) -> pd.DataFrame:
    m = monthly.copy()
    m["year"] = m["date"].str[:4]
    cols = ["n_all", "n_fund", "n_common", "n_ge2b", "n_elig", "n_zero_common", "n_zero_liquid",
            "n_nofund_liquid", "dv_share_ge2b", "dv_share_nocap", "n_adr", "n_other_ex"]
    return m.groupby("year")[cols].mean().round(3)


def render(exp_id: str) -> str:
    d = config.EXPERIMENTS_DIR / exp_id
    res = json.loads((d / "result.json").read_text())
    lines = (d / "messages.txt").read_text().splitlines()
    a = parse_messages(lines)
    (d / "audit_monthly.csv").write_text(results.canonical_csv(a["monthly"]))
    y = yearly_table(a["monthly"])
    p = res["provenance"]
    out = [f"# Data audit ({exp_id}) — measured values", "",
           f"Generated by `python -m qresearch.audit {exp_id}` from QC backtest `{p.get('qc_backtest_id')}` "
           f"(LEAN {p.get('lean_version')}, run {p['run_utc']}, commit `{p['git_commit'][:10]}`). "
           "Interpretation is in the CP2 report.", "",
           "## Yearly averages of the monthly measurements", "",
           "Column meanings: `n_fund` = has Morningstar fundamentals; `n_common` = US common primary share on NYSE/Nasdaq/AMEX; "
           "`n_ge2b` = MarketCap ≥ $2B; `n_elig` = after price ≥ $5 and 20-day average dollar volume ≥ $5M; "
           "`n_zero_liquid` = common stocks with MarketCap = 0 trading at least as much as the 10th-percentile ≥ $2B stock; "
           "`n_nofund_liquid` = the same, but without any fundamentals (includes ETFs); "
           "`dv_share_*` = share of total dollar volume.", "",
           "| Year | " + " | ".join(y.columns) + " |", "|---" * (len(y.columns) + 1) + "|"]
    for yr, row in y.iterrows():
        cells = [f"{v:.0%}" if c.startswith("dv_share") else f"{v:.0f}" for c, v in row.items()]
        out.append(f"| {yr} | " + " | ".join(cells) + " |")
    out += ["", "## Known-company MarketCap snapshots", "",
            "| Target date | Data date | Ticker | QC MarketCap ($B) | Approx. public value ($B) | Has fundamentals |",
            "|---|---|---|---|---|---|"]
    for s in a["snaps"]:
        out.append(f"| {s['target']} | {s['date']} | {s['ticker']} | {s.get('mcap')} | {s.get('ref')} | {s.get('fund', '')} |")
    out += ["", "## Tracked companies (first/last date seen; first/last date with a positive MarketCap)", "",
            "| Ticker | First seen | Last seen | First MarketCap | Last MarketCap |", "|---|---|---|---|---|"]
    for t, r in sorted(a["track"].items()):
        out.append(f"| {t} | {r['first_seen']} | {r['last_seen']} | {r['first_cap'] or 'never'} | {r['last_cap'] or 'never'} |")
    out += ["", "## Most-traded names lacking a MarketCap (first month of each year)", "",
            "| Date | Common stocks with MarketCap = 0 | Securities without fundamentals (incl. ETFs, ADRs) |", "|---|---|---|"]
    for e in a["examples"]:
        out.append(f"| {e['date']} | {e['zero_cap_common']} | {e['no_fundamentals']} |")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    exp_id = (argv or sys.argv[1:] or ["E951-01"])[0]
    text = render(exp_id)
    out = config.REPO_ROOT / "docs" / "data" / "data_audit.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
