"""Build round-trip trades from fills (plus split events) with dollar-based accounting.

A trade opens when a symbol's position goes from flat to long and closes when it returns to flat.
PnL = sell proceeds − buy cost − fees. It is split-invariant because it is measured in dollars.
Dividends are NOT included in trade PnL; they appear in the equity curve (portfolio metrics).
Long-only: a position below zero raises LongOnlyViolation.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd

FILL_COLUMNS = ["order_id", "symbol_id", "symbol", "date", "quantity", "price", "fee", "tag"]
SPLIT_COLUMNS = ["symbol_id", "date", "factor"]
TRADE_COLUMNS = [
    "symbol_id", "symbol", "entry_date", "exit_date", "status", "cost", "proceeds", "fees", "pnl",
    "ret", "n_fills", "max_qty", "exit_tag",
]


class LongOnlyViolation(RuntimeError):
    pass


@dataclass
class _Open:
    symbol: str
    entry_date: str
    cost: float = 0.0
    proceeds: float = 0.0
    fees: float = 0.0
    n_fills: int = 0
    max_qty: float = 0.0
    tags: list[str] = field(default_factory=list)


def build_trades(fills: pd.DataFrame, splits: pd.DataFrame | None = None) -> pd.DataFrame:
    splits = splits if splits is not None else pd.DataFrame(columns=SPLIT_COLUMNS)
    events: list[tuple] = []
    # Splits happen before the open of their date, so they sort before fills on the same date.
    for r in splits.itertuples(index=False):
        events.append((r.symbol_id, str(r.date), 0, 0, ("split", float(r.factor))))
    for r in fills.itertuples(index=False):
        events.append((r.symbol_id, str(r.date), 1, int(r.order_id), ("fill", r)))
    events.sort(key=lambda e: (e[0], e[1], e[2], e[3]))

    qty: dict[str, float] = {}
    open_: dict[str, _Open] = {}
    rows: list[dict] = []
    for sid, day, _, _, (kind, payload) in events:
        q = qty.get(sid, 0.0)
        if kind == "split":
            if q:
                # LEAN truncates fractional shares after a split and pays the remainder in cash.
                qty[sid] = float(int(q / payload + 1e-9))
            continue
        f = payload
        fq = float(f.quantity)
        if q == 0 and fq > 0:
            open_[sid] = _Open(symbol=str(f.symbol), entry_date=day)
        t = open_.get(sid)
        if t is None:
            raise LongOnlyViolation(f"sell of {sid} on {day} without an open position")
        value = abs(fq) * float(f.price)
        if fq > 0:
            t.cost += value
        else:
            t.proceeds += value
        t.fees += float(f.fee)
        t.n_fills += 1
        t.tags.append(str(f.tag))
        q += fq
        t.max_qty = max(t.max_qty, q)
        if q < -1e-9:
            raise LongOnlyViolation(f"{sid} position negative ({q}) on {day}")
        if fq < 0 and q < 1 - 1e-9:
            q = 0.0
            pnl = t.proceeds - t.cost - t.fees
            rows.append(dict(symbol_id=sid, symbol=t.symbol, entry_date=t.entry_date, exit_date=day,
                             status="closed", cost=t.cost, proceeds=t.proceeds, fees=t.fees, pnl=pnl,
                             ret=pnl / t.cost if t.cost else float("nan"), n_fills=t.n_fills,
                             max_qty=t.max_qty, exit_tag=_reason(str(f.tag))))
            del open_[sid]
        qty[sid] = q
    for sid, t in open_.items():
        rows.append(dict(symbol_id=sid, symbol=t.symbol, entry_date=t.entry_date, exit_date="",
                         status="open", cost=t.cost, proceeds=t.proceeds, fees=t.fees,
                         pnl=float("nan"), ret=float("nan"), n_fills=t.n_fills, max_qty=t.max_qty,
                         exit_tag=""))
    out = pd.DataFrame(rows, columns=TRADE_COLUMNS)
    return out.sort_values(["entry_date", "symbol_id", "exit_date"], kind="mergesort").reset_index(drop=True)


def _reason(tag: str) -> str:
    """Harness tags look like 'reason|sig=YYYY-MM-DD'; anything else was generated by LEAN."""
    return tag.split("|", 1)[0] if "|sig=" in tag else "forced"
